version: '3.8'

services:
  plant-service:
    build: .
    container_name: plant-service
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./database:/app/database
    restart: unless-stopped
